name = "bentotui-content"
compatibility_date = "2026-02-24"
pages_build_output_dir = "dist"

# Support wrangler pages deploy
[env.production]
pages_build_output_dir = "dist"

[env.preview]
pages_build_output_dir = "dist"
